spring:
  application:
    name: inventory-service
  datasource:
    username: postgres
    url: jdbc:postgresql://localhost:5432/ecommercedb-dev
    password: '12345'
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
